version: '3.8'

services:
  # 1. SERVICIO DE BASE DE DATOS
  db:
    # Usamos la imagen oficial de MySQL 8.0
    image: mysql:8.0
    container_name: pae_mysql_db
    restart: always
    
    # 2. Variables de entorno: Pasan los valores del .env para configurar MySQL
    environment:
      # Variables esenciales para NestJS (crean la BD y el usuario)
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      
      # Variable necesaria para que MySQL inicie con una contraseña de root
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      
    # 3. Mapeo de puertos (Opcional, solo si necesitas acceder desde tu máquina local)
    # Recomendación: No mapear el puerto si solo el backend lo usará para mayor seguridad.
    ports:
      - "3307:3307"

    # 4. Persistencia de datos (¡CRUCIAL!)
    # Esto asegura que los datos no se pierdan al detener o eliminar el contenedor.
    volumes:
      - pae_data_volume:/var/lib/mysql

# 5. Definición de volúmenes
volumes:
  pae_data_volume:
    driver: local