
name: app_pae
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  qr_flutter: 4.1.0
  mobile_scanner: ^4.0.0
  url_launcher: ^6.3.2
  flutter_native_splash: ^2.4.6
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # Descomenta y agrega esta línea para que Flutter encuentre tu imagen.
  assets:
    - assets/logo3.png

# Esta sección debe estar al mismo nivel que `flutter:`
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo3.png

# Esta sección también debe estar al mismo nivel que `flutter:`
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo3.png
  android: true
  ios: true
  # Estas propiedades se deben indentar dos espacios
  android_gravity: center
  ios_content_mode: scaleAspectFit